api:
  dashboard: true

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/dynamic-conf.yml"

certificatesResolvers:
  http:
    acme:
      email: myemail@mondomaine.com
      storage: acme.json
      # Dev
      caServer: "https://acme-staging.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: http